#!/usr/bin/env python3

import os
from src import *


class Options:
    def __init__(self, data_dir, out_dir):
        self.data_dir = data_dir
        self.out_dir = out_dir


def main():
    current_dir = os.path.dirname(__file__)
    # Last empty path component to ensure that trailing slash is added
    global_opts = Options(os.path.join(current_dir, "data", ""), os.path.join(current_dir, "out", ""))
    os.makedirs(global_opts.out_dir, exist_ok=True)

    # ActiveX
    manage_activex_control(global_opts)
    linking_video_activex_control(global_opts)

    # Metered
    # apply_metered_licensing()

    # Charts
    charts_add_color_to_data_points(global_opts)
    charts_add_custom_error(global_opts)
    charts_add_doughnut_callout(global_opts)
    charts_add_error_bars(global_opts)
    charts_adding_custom_lines(global_opts)
    charts_animating_categories_elements(global_opts)
    charts_animating_series(global_opts)
    charts_animating_series_elements(global_opts)
    charts_automatic_chart_series_color(global_opts)
    charts_box_chart(global_opts)
    charts_calculate_formulas(global_opts)
    charts_change_chart_category_axis(global_opts)
    charts_change_color_of_categories(global_opts)
    charts_data_cell_formulas(global_opts)
    charts_entities_formatting(global_opts)
    charts_get_range()
    charts_get_layout()
    charts_manage_properties(global_opts)
    charts_marker_options_on_data_point(global_opts)
    charts_recover_workbook(global_opts)
    charts_trend_lines(global_opts)
    charts_clear_specific_chart_series_datapoints_data(global_opts)
    charts_create_external_workbook(global_opts)
    charts_data_source_type_property_added(global_opts)
    charts_default_markers(global_opts)
    charts_display_chart_labels(global_opts)
    charts_display_percentage_as_labels(global_opts)
    charts_doughnut_chart_hole(global_opts)
    # charts_edit_chart_data_in_external_workbook(options)
    charts_existing_chart(global_opts)
    charts_font_properties_for_chart(global_opts)
    charts_font_properties_for_invidual_legend(global_opts)
    charts_font_size_legend(global_opts)
    charts_funnel_chart(global_opts)
    charts_get_actual_position_of_chart_data_label(global_opts)
    charts_get_chart_image(global_opts)
    charts_get_values_and_unit_scale_from_axis(global_opts)
    charts_get_width_height_from_chart_plot_area(global_opts)
    charts_hide_information_from_chart(global_opts)
    charts_histogram_chart(global_opts)
    charts_series_invert_if_negative(global_opts)
    charts_map_chart(global_opts)
    charts_multi_category_chart(global_opts)
    charts_normal_charts(global_opts)
    charts_number_format(global_opts)
    charts_organization_chart(global_opts)
    charts_pie_chart(global_opts)
    charts_radar_chart(global_opts)
    charts_scattered_chart(global_opts)
    charts_second_plot_options(global_opts)
    charts_set_automatic_series_fill_color(global_opts)
    charts_set_category_axis_label_distance(global_opts)
    charts_set_chart_series_overlap(global_opts)
    charts_set_data_labels_percentage_sign(global_opts)
    # charts_set_data_range(global_opts)
    charts_set_external_workbook(global_opts)
    charts_set_external_workbook_with_update_chart_data(global_opts)
    charts_set_gap_width(global_opts)
    charts_set_invert_fill_color_chart(global_opts)
    charts_set_layout_mode(global_opts)
    charts_set_legend_custom_options(global_opts)
    charts_set_marker_options(global_opts)
    charts_setting_automic_pie_chart_slice_colors(global_opts)
    charts_setting_callout_for_data_label(global_opts)
    charts_setting_date_format_for_category_axis(global_opts)
    charts_setting_font_properties(global_opts)
    charts_setting_position_axis(global_opts)
    charts_setting_rotation_angle(global_opts)
    charts_showing_display_unit_label(global_opts)
    charts_sunburst_chart(global_opts)
    charts_support_for_bubble_chart_scaling(global_opts)
    charts_changing_series_color(global_opts)
    charts_precision_of_data(global_opts)
    charts_stock_chart(global_opts)
    charts_bubble_size_representation(global_opts)
    charts_time_unit_type_enum(global_opts)
    charts_tree_map_chart(global_opts)
    charts_workbook_as_datalabel(global_opts)
    charts_validate_chart_layout(global_opts)
    charts_worksheets_example(global_opts)

    # Presentations conversion
    convert_to_tiff_notes(global_opts)
    # convert_html_embedding_images(global_opts)
    convert_notes_to_pdf(global_opts)
    convert_to_password_protected_pdf(global_opts)
    convert_to_responsive_html(global_opts)
    convert_to_pdf_notes(global_opts)
    convert_specific_slide_to_pdf(global_opts)
    convert_to_black_white_tiff(global_opts)
    convert_to_gif(global_opts)
    convert_to_handout(global_opts)
    convert_to_html5_notes_comments(global_opts)
    convert_to_html5(global_opts)
    convert_to_markdown(global_opts)
    convert_to_pdf_compliance(global_opts)
    convert_to_pdf_hidden_slides(global_opts)
    convert_to_pdf_with_compliance(global_opts)
    convert_to_pdf(global_opts)
    convert_to_swf(global_opts)
    convert_to_html_with_media(global_opts)
    convert_to_tiff_custom_size(global_opts)
    convert_to_tiff_with_notes(global_opts)
    convert_to_xps_with_options(global_opts)
    convert_to_xps(global_opts)
    convert_to_html_with_embed_all_fonts(global_opts)
    convert_to_html_with_preserving_original_fonts(global_opts)
    create_new_presentation(global_opts)
    convert_to_pdf_custom_options(global_opts)
    export_ink_example(global_opts)
    export_math_paragraph_to_latex()
    export_math_paragraph_to_math_ml(global_opts)
    export_shape_to_svg(global_opts)
    convert_to_html_with_responsive_layout(global_opts)
    convert_to_fodp(global_opts)
    convert_to_odp(global_opts)
    import_from_pdf(global_opts)
    convert_to_ppt(global_opts)
    convert_to_tiff_image_pixel_format(global_opts)
    convert_to_tiff(global_opts)
    convert_to_html_with_notes(global_opts)
    slide_show_media_controls(global_opts)

    # Presentation opening
    get_file_format(global_opts)
    get_position_coordinates_of_portion(global_opts)
    get_rectangular_coordinates_of_paragraph(global_opts)
    load_format_enumeration(global_opts)
    open_password_presentation(global_opts)
    open_presentation(global_opts)
    open_very_large_presentation(global_opts)
    open_set_access_permissions_to_pdf(global_opts)

    # Presentation properties
    props_access_builtin_properties(global_opts)
    props_access_layout_formats(global_opts)
    props_access_modifying_properties(global_opts)
    props_access_properties()
    props_add_blob_to_presentation(global_opts)
    props_add_custom_document_properties(global_opts)
    props_check_password(global_opts)
    props_check_presentation_protection(global_opts)
    insert_svg(global_opts)
    props_modify_builtin_properties(global_opts)
    props_read_only_recommended(global_opts)
    props_update_presentation_properties(global_opts)
    props_update_properties_using_template(global_opts)

    # Presentation saving
    save_add_blob_image(global_opts)
    save_convert_svg_to_group_of_shapes(global_opts)
    save_remove_write_protection(global_opts)
    save_as_predefined_view_type(global_opts)
    save_as_read_only(global_opts)
    save_properties(global_opts)
    save_to_file(global_opts)
    save_to_stream(global_opts)
    save_with_password(global_opts)
    save_add_digital_signature(global_opts)

    # Rendering printing
    # printing_default_settings(global_opts)
    # printing_preview()
    rendering_comments(global_opts)
    rendering_options(global_opts)
    rendering_3d(global_opts)
    rendering_emoji(global_opts)
    rendering_set_slide_number(global_opts)
    rendering_set_zoom(global_opts)

    # Shapes
    shapes_accessing_ole_object_frame(global_opts)
    shapes_accessing_alt_text(global_opts)
    shapes_add_arrow_shaped_line(global_opts)
    shapes_add_audio_frame(global_opts)
    shapes_add_ole_object_frame(global_opts)
    add_plain_line_to_slide(global_opts)
    add_relative_scale_height_picture_frame(global_opts)
    add_stretch_offset_for_image_fill(global_opts)
    # Exception with HTTP error 404 on image link
    # add_video_frame_from_web_source(global_opts)
    add_video_frame(global_opts)
    animation_target_shapes(global_opts)
    animation_on_shapes(global_opts)
    apply_3d_rotation_effect_on_shape(global_opts)
    apply_bevel_effects(global_opts)
    change_shape_order(global_opts)
    clone_shapes(global_opts)
    connect_shape_using_connection_site(global_opts)
    connect_shapes_using_connectors(global_opts)
    connector_line_angle(global_opts)
    create_bounds_shape_thumbnail(global_opts)
    create_group_shape(global_opts)
    create_scaling_factor_thumbnail(global_opts)
    create_section_zoom(global_opts)
    create_shape_thumbnail(global_opts)
    create_smart_art_child_note_thumbnail(global_opts)
    create_summary_zoom(global_opts)
    create_zoom_frame(global_opts)
    delete_picture_cropped_areas_example(global_opts)
    duotone_effects_pvi(global_opts)
    embedded_video_frame(global_opts)
    extract_embedded_file_data_from_ole_object(global_opts)
    fill_shapes_gradient(global_opts)
    fill_shapes_pattern(global_opts)
    fill_shapes_picture(global_opts)
    fill_shapes_with_solid_color(global_opts)
    find_shape_in_slide(global_opts)
    format_join_styles(global_opts)
    format_lines(global_opts)
    formatted_eclipse(global_opts)
    formatted_rectangle(global_opts)
    geometry_shape_add_segment(global_opts)
    geometry_shape_composite_objects(global_opts)
    geometry_shape_creates_custom_geometry(global_opts)
    geometry_shape_remove_segment(global_opts)
    geometry_shape_using_shape_util(global_opts)
    get_camera_effective_data(global_opts)
    get_light_rig_effective_data(global_opts)
    get_shape_bevel_effective_data(global_opts)
    hiding_shapes(global_opts)
    ink_management_example(global_opts)
    interop_shape_id(global_opts)
    math_shape_get_children(global_opts)
    mathematical_shape(global_opts)
    picture_frame_formatting(global_opts)
    remove_shape(global_opts)
    rotating_shapes_example(global_opts)
    set_alternative_text(global_opts)
    set_file_type_for_an_embedding_object(global_opts)
    set_video_trim_from_end(global_opts)
    shape_is_decorative_property_example(global_opts)
    shapes_alignment(global_opts)
    simple_ellipse(global_opts)
    simple_rectangle(global_opts)
    sketched_shapes(global_opts)
    stretch_offset_left_for_picture_frame(global_opts)
    substitute_picture_title_of_ole_object_frame(global_opts)

    # Slides background
    get_background_effective_values(global_opts)
    set_background_to_gradient(global_opts)
    set_image_as_background(global_opts)
    set_slide_background_master(global_opts)
    set_slide_background_normal(global_opts)

    # Slides comments
    access_slide_comments(global_opts)
    add_parent_comments(global_opts)
    add_slide_comments(global_opts)
    modern_comments(global_opts)

    # Slides CRUD
    access_slide_by_id(global_opts)
    access_slide_by_index(global_opts)
    access_slides(global_opts)
    add_notes_slide_with_notes_style(global_opts)
    add_slides(global_opts)
    change_position(global_opts)
    clone_another_presentation_at_specified_position(global_opts)
    clone_at_end_of_another(global_opts)
    clone_slide_into_specified_section(global_opts)
    clone_to_another_presentation_with_master(global_opts)
    clone_within_same_presentation_to_end(global_opts)
    clone_within_same_presentation(global_opts)
    create_slides_svg_image(global_opts)
    remove_slide_using_index(global_opts)
    remove_slides_using_reference(global_opts)
    section_collection(global_opts)

    # Slides hyperlink
    add_hyperlink(global_opts)
    macro_hyperlink()
    remove_hyperlinks(global_opts)
    set_hyperlink_color(global_opts)

    # Slides layout
    add_layout_slides(global_opts)
    check_slides_comparison(global_opts)
    get_base_placeholder_example(global_opts)
    header_footer_manager_example(global_opts)
    manage_header_footer_text(global_opts)
    set_child_footer(global_opts)
    set_pdf_page_size(global_opts)
    set_size_and_type(global_opts)
    set_slide_size_scale(global_opts)

    # Slides media
    extract_audio(global_opts)
    extract_audio_from_hyperlink(global_opts)
    extract_video(global_opts)
    stop_previous_sound_example(global_opts)

    # Slides notes
    header_and_footer_in_notes_slide(global_opts)
    remove_notes_at_specific_slide(global_opts)

    # Slides thumbnail
    thumbnail_from_slide(global_opts)
    thumbnail_from_slide_in_notes(global_opts)
    thumbnail_with_user_defined_dimensions(global_opts)

    # Slides transitions
    after_animation_type_example(global_opts)
    animation_rewind(global_opts)
    better_slide_transitions(global_opts)
    manage_simple_slide_transitions(global_opts)
    managing_better_slide_transitions(global_opts)
    set_transition_effects(global_opts)
    set_transition_morph_type(global_opts)
    simple_slide_transitions(global_opts)
    support_of_morph_transition(global_opts)

    # Slides views
    manage_presentation_normal_view_state(global_opts)

    # Smart Arts
    access_child_node_specific_position()
    access_child_nodes(global_opts)
    access_smart_art(global_opts)
    access_smart_art_particular_layout(global_opts)
    access_smart_art_shape(global_opts)
    add_nodes(global_opts)
    add_nodes_specific_position(global_opts)
    assistant_node(global_opts)
    bullet_fill_format_example(global_opts)
    change_smart_art_layout(global_opts)
    change_smart_art_shape_color_style(global_opts)
    change_smart_art_shape_style(global_opts)
    change_smart_art_state(global_opts)
    change_text_on_smart_art_node(global_opts)
    check_smart_art_hidden_property(global_opts)
    create_smart_art_shape(global_opts)
    custom_child_nodes_in_smart_art(global_opts)
    fill_format_smart_art_shape_node(global_opts)
    organize_chart_layout_type(global_opts)
    remove_node_example(global_opts)
    remove_node_specific_position(global_opts)

    # Slides tables
    add_image_inside_table_cell(global_opts)
    add_image_inside_table_cell_and_crop(global_opts)
    cell_split(global_opts)
    cloning_in_table(global_opts)
    create_table(global_opts)
    create_table_from_scratch_in_slide(global_opts)
    get_effective_values_of_table(global_opts)
    identifying_the_merged_cells_in_table(global_opts)
    lock_aspect_ratio(global_opts)
    merge_cell(global_opts)
    removing_row_column(global_opts)
    resize_slide_with_table(global_opts)
    set_first_row_as_header(global_opts)
    set_text_formatting_inside_table(global_opts)
    standard_tables(global_opts)
    table_from_scratch(global_opts)
    table_with_cell_borders(global_opts)
    text_formatting_inside_table_column(global_opts)
    text_formatting_inside_table_row(global_opts)
    vertically_align_text(global_opts)

    # Slides text
    add_column_in_text_boxes(global_opts)
    add_columns_in_text_frame(global_opts)
    add_custom_prompt_text(global_opts)
    add_embedded_fonts(global_opts)
    adding_superscript_and_subscript_text_in_text_frame(global_opts)
    animate_text_type_example(global_opts)
    animation_effect_in_paragraph(global_opts)
    apply_inner_shadow(global_opts)
    apply_outer_shadow(global_opts)
    bullet_fill_format_effective(global_opts)
    custom_rotation_angle_text_frame(global_opts)
    default_fonts_example(global_opts)
    effect_text_box_paragraph(global_opts)
    end_para_graph_properties(global_opts)
    exporting_html_text(global_opts)
    fallback_rules_collection()
    find_and_replace_text(global_opts)
    font_family_example(global_opts)
    font_properties_example(global_opts)
    get_effective_values(global_opts)
    get_fonts_folder()
    get_text_style_effective_data(global_opts)
    get_text_from_smart_art_node(global_opts)
    get_text_style_effective_data(global_opts)
    highlight_text(global_opts)
    highlight_text_using_regex(global_opts)
    importing_html_text(global_opts)
    keep_text_flat(global_opts)
    line_spacing(global_opts)
    load_external_font_example(global_opts)
    manage_embedded_fonts(global_opts)
    manage_paragraph_font_properties(global_opts)
    manage_paragraph_picture_bullets_in_ppt(global_opts)
    multiple_paragraphs(global_opts)
    multi_level_bullets(global_opts)
    number_lines_in_paragraph()
    paragraph_bullets(global_opts)
    paragraph_indent(global_opts)
    paragraphs_alignment(global_opts)
    portion_get_rect(global_opts)
    rendering_with_fallback_font(global_opts)
    replace_fonts_explicitly(global_opts)
    replacing_text(global_opts)
    rotating_text(global_opts)
    rule_based_fonts_replacement(global_opts)
    save_with_default_regular_font(global_opts)
    set_anchor_of_text_frame(global_opts)
    set_autofit_of_text_frame(global_opts)
    set_custom_bullets_number(global_opts)
    set_local_font_height_values(global_opts)
    set_text_font_properties(global_opts)
    set_transparency_of_text_in_shadow(global_opts)
    setting_presentation_language_and_shape_text(global_opts)
    shadow_effects(global_opts)
    specify_default_text_language()
    text_box_hyperlink(global_opts)
    text_box_on_slide_program(global_opts)
    use_custom_fonts(global_opts)
    word_art_example(global_opts)

    # VBA
    add_vba_macros(global_opts)
    extracting_vba_macros(global_opts)
    remove_vba_macros(global_opts)


if __name__ == "__main__":
    main()
